const OPEN_DIALOG = 'OPEN_DIALOG';
const CLOSE_DIALOG = 'CLOSE_DIALOG';
const ADD_TASK_DIALOG = 'ADD_TASK_DIALOG';
const EDIT_TASK_DIALOG = 'EDIT_TASK_DIALOG';

export const typeDialog = {
  OPEN_DIALOG,
  CLOSE_DIALOG,
  ADD_TASK_DIALOG,
  EDIT_TASK_DIALOG,
};
