const GET_TASK = 'GET_TASK';
const GET_TASK_SUCCEEDED = 'GET_TASK_SUCCEEDED';
const GET_TASK_FAILED = 'GET_TASK_FAILED';
const GET_ALL_TASKS = 'GET_ALL_TASKS';
const GET_ALL_TASKS_SUCCEEDED = 'GET_ALL_TASKS_SUCCEEDED';
const GET_ALL_TASKS_FAILED = 'GET_ALL_TASKS_FAILED';
const REMOVE_TASK = 'REMOVE_TASK';
const REMOVE_TASK_SUCCEEDED = 'REMOVE_TASK_SUCCEEDED';
const REMOVE_TASK_FAILED = 'REMOVE_TASK_FAILED';
const UPDATE_TASK = 'UPDATE_TASK';
const UPDATE_TASK_SUCCEEDED = 'UPDATE_TASK_SUCCEEDED';
const UPDATE_TASK_FAILED = 'UPDATE_TASK_FAILED';
const ADD_TASK = 'ADD_TASK';
const ADD_TASK_SUCCEEDED = 'ADD_TASK_SUCCEEDED';
const ADD_TASK_FAILED = 'ADD_TASK_FAILED';
const CLEAR_TYPE_TODO_LIST = 'CLEAR_TYPE_TODO_LIST';

export const typeTodoList = {
  GET_TASK,
  GET_TASK_SUCCEEDED,
  GET_ALL_TASKS,
  GET_TASK_FAILED,
  GET_ALL_TASKS_SUCCEEDED,
  GET_ALL_TASKS_FAILED,
  REMOVE_TASK,
  REMOVE_TASK_SUCCEEDED,
  REMOVE_TASK_FAILED,
  UPDATE_TASK,
  UPDATE_TASK_SUCCEEDED,
  UPDATE_TASK_FAILED,
  ADD_TASK,
  ADD_TASK_SUCCEEDED,
  ADD_TASK_FAILED,
  CLEAR_TYPE_TODO_LIST,
};
