const SIGN_IN = 'SIGN_IN';
const SIGN_IN_SUCCEEDED = 'SIGN_IN_SUCCEEDED';
const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
const SIGN_OUT = 'SIGN_OUT';
const SIGN_OUT_SUCCEEDED = 'SIGN_OUT_SUCCEEDED';
const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED';
const SIGN_UP = 'SIGN_UP';
const SIGN_UP_SUCCEEDED = 'SIGN_UP_SUCCEEDED';
const SIGN_UP_FAILED = 'SIGN_UP_FAILED';
const UPDATE_USER = 'UPDATE_USER';
const UPDATE_USER_SUCCEEDED = 'UPDATE_USER_SUCCEEDED';
const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED ';
const CLEAR_TYPE_USER = 'CLEAR_TYPE_USER';

export const typeUser = {
  SIGN_IN,
  SIGN_IN_SUCCEEDED,
  SIGN_IN_FAILED,
  SIGN_OUT,
  SIGN_OUT_SUCCEEDED,
  SIGN_OUT_FAILED,
  SIGN_UP,
  SIGN_UP_SUCCEEDED,
  SIGN_UP_FAILED,
  UPDATE_USER,
  UPDATE_USER_SUCCEEDED,
  UPDATE_USER_FAILED,
  CLEAR_TYPE_USER,
};
